Runner_site_on_django/runner/run_plan/urls.py
from django.urls import path

from .views import runplan

# Пространство имен
app_name = 'run_plan'

urlpatterns = [
    path('', runplan, name='runplan'),
]

Runner_site_on_django/runner/runner/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, video

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),

    path('video/', video, name='video'),
    path('runplan/', include('run_plan.urls', namespace='runplan')),
]

Runner_site_on_django/runner/run_plan/models.py
from django.db import models

# Create your models here.

Runner_site_on_django/runner/run_plan/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.template import loader


def runplan(request):
    template = loader.get_template('runplan/runplan.html')
    return HttpResponse(template.render())

Runner_site_on_django/runner/runner/views.py
from django.http import HttpResponse
from django.template import loader


def index(request):
    template = loader.get_template('runner/index.html')
    return HttpResponse(template.render())


def video(request):
    template = loader.get_template('runner/video.html')
    return HttpResponse(template.render())

Runner_site_on_django/runner/run_plan/templates/runplan/runplan.html
{% extends 'runner/base.html' %}
{% load static %}

{% block title %} Run plan {% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="mid-box-runplun">
            <a href="#">
                <div class="g-card runner-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/clipboard.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Мои первые 5 км за 4 недели</h4>
                        <p>Скачать PDF</p>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="g-card runner-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/running.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Мои первые 10 км за 4 недели</h4>
                        <p>Платный курс. Только после успешного преодоления дистанции 5км быстрее 35 минут</p>
                    </div>
                </div>
            </a>
           <a href="#">
                <div class="g-card runner-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/smartwatch.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Мой первый полумарафон 21.1 км за 8 недель</h4>
                        <p>Платный курс. Только после успешного преодоления дистанции 10км быстрее 70 минут</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</main>
{% endblock %}

Runner_site_on_django/runner/runner/templates/runner/base.html
<!DOCTYPE html>

{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'runner/assets/icons/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link href="{% static 'runner/assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'runner/assets/css/style.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=Roboto+Slab&display=swap"
          rel="stylesheet">
</head>
<body id="bg" style="background-image: url('{% static 'runner/assets/images/backstory2.png' %}');">


<div class="wrapper">
    <!-- Header -->
    <header class="page-header">
        <div class="container">
            <div class="pre-header">
                <div class="title-top">
                    <h2>FIND YOUR</h2>
                    <h2>"Зеленая книга"</h2>
                </div>
                <div class="title-mid">
                    <h1>GREENZONE</h1>
                    <h3>Методическое пособие по подготовке к городским забегам и для души</h3>
                </div>
            </div>
        </div>
    </header>
    <!-- End Header -->
    <main class="page-body">
        {% block content %}

        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="sub-footer">
            <p>CodeAgain production</p>
            <p>2021 - {% now "Y" %}</p>
        </div>
    </footer>
</div>

<!-- Bootstrap Bundle with Popper -->
<script src="{% static 'runner/assets/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

Runner_site_on_django/runner/runner/templates/runner/index.html
{% extends 'runner/base.html' %}
{% load static %}

{% block title %} Runner {% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="mid-box">
            <a href="#">
                <div class="g-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/book.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Зеленая книга | Find Your Green Zone</h4>
                        <p>Обучающий буклет по бегу для начинающих</p>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="g-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/youtube.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Обучающий фильм по бегу для начиющих</h4>
                        <p>Расширенное дополнение к буклету</p>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="g-card g-gradient">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/running.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body g-ref">
                        <h4>Зарегистироваться на Алматы Марафон</h4>
                    </div>
                </div>
            </a>
            <a href="{% url 'runplan:runplan' %}">
                <div class="g-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/clipboard.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Скачать беговой план</h4>
                        <p>Самостоятельная подготовка к городским забегам</p>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="g-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/medal.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                            <h4>Живые тренировки в команде ANR Pro Runners</h4>
                            <p>3 раза в неделю, в Алматы, платно.</p>
                    </div>
                </div>
            </a>
            <a href="{% url 'video' %}">
                <div class="g-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/film.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                            <h4>Видео примеры упражнений</h4>
                            <p>Разминка, медленный бег, заминка</p>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="g-card g-card-last">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/telegram.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body g-card-last">
                        <h4>Добавиться в группу Telegram</h4>
                    </div>
                </div>
            </a>
        </div>
    </div>
</main>
{% endblock %}

Runner_site_on_django/runner/runner/templates/runner/video.html
{% extends 'runner/base.html' %}
{% load static %}

{% block title %} Video {% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="mid-box-runplun">
            <a href="#">
                <div class="g-card video-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/youtube.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Суставная разминка перед пробежкой</h4>
                        <p>5 минут</p>
                    </div>
                </div>
            </a>
            <a href="#">
                <div class="g-card video-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/youtube.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Растяжка мышц после пробежки</h4>
                        <p>5 минут</p>
                    </div>
                </div>
            </a>
           <a href="#">
                <div class="g-card video-card">
                    <div class="g-side">
                        <div class="back">
                            <img src="{% static 'runner/assets/icons/youtube.png' %}" width="30px" alt="book">
                        </div>
                    </div>
                    <div class="g-card-body">
                        <h4>Пример бега в зеленой зоне</h4>
                        <p>1 минута</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</main>
{% endblock %}